-- 003: town -> MET district crosswalk (reference data).
-- Only rows that cannot be derived from name identity (a city whose name differs
-- from its district). The rest are computed at read time from the locality list and
-- the district registry, so there is no generated file and no separate data format.
-- NOTE: the town->district half is a person's assertion; the district->state half
-- comes from MET's own district selector.
CREATE TABLE IF NOT EXISTS town_districts (
  town_slug     TEXT PRIMARY KEY,
  district_name TEXT NOT NULL,
  source        TEXT NOT NULL,
  asserted_at   TEXT NOT NULL
);

INSERT INTO town_districts (town_slug, district_name, source, asserted_at) VALUES ('alor-setar','Kota Setar','manual assertion, state via MET district selector','2026-09-11') ON CONFLICT(town_slug) DO UPDATE SET district_name=excluded.district_name, source=excluded.source, asserted_at=excluded.asserted_at;
INSERT INTO town_districts (town_slug, district_name, source, asserted_at) VALUES ('arau','Perlis','manual assertion, state via MET district selector','2026-09-11') ON CONFLICT(town_slug) DO UPDATE SET district_name=excluded.district_name, source=excluded.source, asserted_at=excluded.asserted_at;
INSERT INTO town_districts (town_slug, district_name, source, asserted_at) VALUES ('ayer-keroh','Melaka Tengah','manual assertion, state via MET district selector','2026-09-11') ON CONFLICT(town_slug) DO UPDATE SET district_name=excluded.district_name, source=excluded.source, asserted_at=excluded.asserted_at;
INSERT INTO town_districts (town_slug, district_name, source, asserted_at) VALUES ('balik-pulau','Barat Daya','manual assertion, state via MET district selector','2026-09-11') ON CONFLICT(town_slug) DO UPDATE SET district_name=excluded.district_name, source=excluded.source, asserted_at=excluded.asserted_at;
INSERT INTO town_districts (town_slug, district_name, source, asserted_at) VALUES ('banting','Kuala Langat','manual assertion, state via MET district selector','2026-09-11') ON CONFLICT(town_slug) DO UPDATE SET district_name=excluded.district_name, source=excluded.source, asserted_at=excluded.asserted_at;
INSERT INTO town_districts (town_slug, district_name, source, asserted_at) VALUES ('bukit-mertajam','Seberang Perai Tengah','manual assertion, state via MET district selector','2026-09-11') ON CONFLICT(town_slug) DO UPDATE SET district_name=excluded.district_name, source=excluded.source, asserted_at=excluded.asserted_at;
INSERT INTO town_districts (town_slug, district_name, source, asserted_at) VALUES ('butterworth','Seberang Perai Utara','manual assertion, state via MET district selector','2026-09-11') ON CONFLICT(town_slug) DO UPDATE SET district_name=excluded.district_name, source=excluded.source, asserted_at=excluded.asserted_at;
INSERT INTO town_districts (town_slug, district_name, source, asserted_at) VALUES ('cameron-highlands','Tanah Tinggi Cameron','manual assertion, state via MET district selector','2026-09-11') ON CONFLICT(town_slug) DO UPDATE SET district_name=excluded.district_name, source=excluded.source, asserted_at=excluded.asserted_at;
INSERT INTO town_districts (town_slug, district_name, source, asserted_at) VALUES ('george-town','Timur Laut','manual assertion, state via MET district selector','2026-09-11') ON CONFLICT(town_slug) DO UPDATE SET district_name=excluded.district_name, source=excluded.source, asserted_at=excluded.asserted_at;
INSERT INTO town_districts (town_slug, district_name, source, asserted_at) VALUES ('gerik','Hulu Perak','manual assertion, state via MET district selector','2026-09-11') ON CONFLICT(town_slug) DO UPDATE SET district_name=excluded.district_name, source=excluded.source, asserted_at=excluded.asserted_at;
INSERT INTO town_districts (town_slug, district_name, source, asserted_at) VALUES ('ipoh','Kinta','manual assertion, state via MET district selector','2026-09-11') ON CONFLICT(town_slug) DO UPDATE SET district_name=excluded.district_name, source=excluded.source, asserted_at=excluded.asserted_at;
INSERT INTO town_districts (town_slug, district_name, source, asserted_at) VALUES ('kajang','Hulu Langat','manual assertion, state via MET district selector','2026-09-11') ON CONFLICT(town_slug) DO UPDATE SET district_name=excluded.district_name, source=excluded.source, asserted_at=excluded.asserted_at;
INSERT INTO town_districts (town_slug, district_name, source, asserted_at) VALUES ('kangar','Perlis','manual assertion, state via MET district selector','2026-09-11') ON CONFLICT(town_slug) DO UPDATE SET district_name=excluded.district_name, source=excluded.source, asserted_at=excluded.asserted_at;
INSERT INTO town_districts (town_slug, district_name, source, asserted_at) VALUES ('kuala-berang','Hulu Terengganu','manual assertion, state via MET district selector','2026-09-11') ON CONFLICT(town_slug) DO UPDATE SET district_name=excluded.district_name, source=excluded.source, asserted_at=excluded.asserted_at;
INSERT INTO town_districts (town_slug, district_name, source, asserted_at) VALUES ('kuala-kubu-bharu','Hulu Selangor','manual assertion, state via MET district selector','2026-09-11') ON CONFLICT(town_slug) DO UPDATE SET district_name=excluded.district_name, source=excluded.source, asserted_at=excluded.asserted_at;
INSERT INTO town_districts (town_slug, district_name, source, asserted_at) VALUES ('lenggong','Hulu Perak','manual assertion, state via MET district selector','2026-09-11') ON CONFLICT(town_slug) DO UPDATE SET district_name=excluded.district_name, source=excluded.source, asserted_at=excluded.asserted_at;
INSERT INTO town_districts (town_slug, district_name, source, asserted_at) VALUES ('masjid-tanah','Alor Gajah','manual assertion, state via MET district selector','2026-09-11') ON CONFLICT(town_slug) DO UPDATE SET district_name=excluded.district_name, source=excluded.source, asserted_at=excluded.asserted_at;
INSERT INTO town_districts (town_slug, district_name, source, asserted_at) VALUES ('melaka-city','Melaka Tengah','manual assertion, state via MET district selector','2026-09-11') ON CONFLICT(town_slug) DO UPDATE SET district_name=excluded.district_name, source=excluded.source, asserted_at=excluded.asserted_at;
INSERT INTO town_districts (town_slug, district_name, source, asserted_at) VALUES ('nibong-tebal','Seberang Perai Selatan','manual assertion, state via MET district selector','2026-09-11') ON CONFLICT(town_slug) DO UPDATE SET district_name=excluded.district_name, source=excluded.source, asserted_at=excluded.asserted_at;
INSERT INTO town_districts (town_slug, district_name, source, asserted_at) VALUES ('parit-buntar','Kerian','manual assertion, state via MET district selector','2026-09-11') ON CONFLICT(town_slug) DO UPDATE SET district_name=excluded.district_name, source=excluded.source, asserted_at=excluded.asserted_at;
INSERT INTO town_districts (town_slug, district_name, source, asserted_at) VALUES ('pasir-gudang','Johor Bahru','manual assertion, state via MET district selector','2026-09-11') ON CONFLICT(town_slug) DO UPDATE SET district_name=excluded.district_name, source=excluded.source, asserted_at=excluded.asserted_at;
INSERT INTO town_districts (town_slug, district_name, source, asserted_at) VALUES ('pengerang','Kota Tinggi','manual assertion, state via MET district selector','2026-09-11') ON CONFLICT(town_slug) DO UPDATE SET district_name=excluded.district_name, source=excluded.source, asserted_at=excluded.asserted_at;
INSERT INTO town_districts (town_slug, district_name, source, asserted_at) VALUES ('permaisuri','Setiu','manual assertion, state via MET district selector','2026-09-11') ON CONFLICT(town_slug) DO UPDATE SET district_name=excluded.district_name, source=excluded.source, asserted_at=excluded.asserted_at;
INSERT INTO town_districts (town_slug, district_name, source, asserted_at) VALUES ('petaling-jaya','Petaling','manual assertion, state via MET district selector','2026-09-11') ON CONFLICT(town_slug) DO UPDATE SET district_name=excluded.district_name, source=excluded.source, asserted_at=excluded.asserted_at;
INSERT INTO town_districts (town_slug, district_name, source, asserted_at) VALUES ('shah-alam','Petaling','manual assertion, state via MET district selector','2026-09-11') ON CONFLICT(town_slug) DO UPDATE SET district_name=excluded.district_name, source=excluded.source, asserted_at=excluded.asserted_at;
INSERT INTO town_districts (town_slug, district_name, source, asserted_at) VALUES ('sitiawan','Manjung','manual assertion, state via MET district selector','2026-09-11') ON CONFLICT(town_slug) DO UPDATE SET district_name=excluded.district_name, source=excluded.source, asserted_at=excluded.asserted_at;
INSERT INTO town_districts (town_slug, district_name, source, asserted_at) VALUES ('subang-jaya','Petaling','manual assertion, state via MET district selector','2026-09-11') ON CONFLICT(town_slug) DO UPDATE SET district_name=excluded.district_name, source=excluded.source, asserted_at=excluded.asserted_at;
INSERT INTO town_districts (town_slug, district_name, source, asserted_at) VALUES ('sungai-petani','Kuala Muda','manual assertion, state via MET district selector','2026-09-11') ON CONFLICT(town_slug) DO UPDATE SET district_name=excluded.district_name, source=excluded.source, asserted_at=excluded.asserted_at;
INSERT INTO town_districts (town_slug, district_name, source, asserted_at) VALUES ('taiping','Larut, Matang Dan Selama','manual assertion, state via MET district selector','2026-09-11') ON CONFLICT(town_slug) DO UPDATE SET district_name=excluded.district_name, source=excluded.source, asserted_at=excluded.asserted_at;
INSERT INTO town_districts (town_slug, district_name, source, asserted_at) VALUES ('tanjung-karang','Kuala Selangor','manual assertion, state via MET district selector','2026-09-11') ON CONFLICT(town_slug) DO UPDATE SET district_name=excluded.district_name, source=excluded.source, asserted_at=excluded.asserted_at;
INSERT INTO town_districts (town_slug, district_name, source, asserted_at) VALUES ('tanjung-malim','Muallim','manual assertion, state via MET district selector','2026-09-11') ON CONFLICT(town_slug) DO UPDATE SET district_name=excluded.district_name, source=excluded.source, asserted_at=excluded.asserted_at;
INSERT INTO town_districts (town_slug, district_name, source, asserted_at) VALUES ('teluk-intan','Hilir Perak','manual assertion, state via MET district selector','2026-09-11') ON CONFLICT(town_slug) DO UPDATE SET district_name=excluded.district_name, source=excluded.source, asserted_at=excluded.asserted_at;
